const placesData = [
  {
    id: 1,
    name: "Cafetería Plaza Centenario",
    description: "Cafetería central con gran variedad de snacks y bebidas para disfrutar entre clases.",
    priceRange: "$$",
    distanceText: "1 min",
    category: "Cafetería",
    schedule: "Lun-Vie: 7:00 AM - 9:00 PM",
    image: "img/1.jpg",
    lat: 21.1532,
    lng: -101.7110,
    address: "Universidad De La Salle Bajío, Plaza Centenario",
    phone: "(477) 382-9102"
  },
  {
    id: 2,
    name: "El Rincón",
    description: "Conocida como la cafetería de bubas, ubicada entre negocios e ingenierías.",
    priceRange: "$",
    distanceText: "3 min",
    category: "Bebidas y Snacks",
    schedule: "Lun-Vie: 8:00 AM - 6:00 PM",
    image: "img/2.jpg",
    lat: 21.1530,
    lng: -101.7095,
    address: "Universidad De La Salle Bajío, Entre Negocios e Ingenierías",
    phone: "(477) 819-3341"
  },
  {
    id: 3,
    name: "Pizzería Fratelo Gastronomía",
    description: "Deliciosas pizzas y comida italiana con un toque estudiantil.",
    priceRange: "$$$",
    distanceText: "5 min",
    category: "Pizza",
    schedule: "Lun-Sáb: 10:00 AM - 8:00 PM",
    image: "img/3.jpg",
    lat: 21.1538,
    lng: -101.7098,
    address: "Universidad De La Salle Bajío, Cerca de Gastronomía",
    phone: "(477) 502-1847"
  },
  {
    id: 4,
    name: "Cafetería Facultad de Negocios",
    description: "Lugar ideal para desayunar o comer algo rápido antes de tus clases de negocios.",
    priceRange: "$$",
    distanceText: "2 min",
    category: "Cafetería",
    schedule: "Lun-Vie: 7:00 AM - 8:00 PM",
    image: "img/4.jpg",
    lat: 21.1536,
    lng: -101.7102,
    address: "Universidad De La Salle Bajío, Facultad de Negocios",
    phone: "(477) 293-8475"
  },
  {
    id: 5,
    name: "Leaf & Brew",
    description: "Café de especialidad y ambiente tranquilo en la Facultad de Negocios.",
    priceRange: "$$$",
    distanceText: "2 min",
    category: "Café",
    schedule: "Lun-Vie: 8:00 AM - 7:00 PM",
    image: "img/5.jpg",
    lat: 21.1537,
    lng: -101.7100,
    address: "Universidad De La Salle Bajío, Facultad de Negocios",
    phone: "(477) 746-1928"
  },
  {
    id: 6,
    name: "Plaza San Juan Bautista",
    description: "Zona de comidas en la plaza, excelente para relajarse al aire libre.",
    priceRange: "$$",
    distanceText: "4 min",
    category: "Comida Variada",
    schedule: "Lun-Vie: 8:00 AM - 5:00 PM",
    image: "img/6.jpg",
    lat: 21.1523,
    lng: -101.7118,
    address: "Universidad De La Salle Bajío, Plaza San Juan Bautista",
    phone: "(477) 381-0029"
  },
  {
    id: 7,
    name: "Cafetería Comunicación - Odontología",
    description: "Punto de encuentro para estudiantes de comunicación y odontología con antojitos variados.",
    priceRange: "$",
    distanceText: "3 min",
    category: "Cafetería",
    schedule: "Lun-Vie: 7:00 AM - 6:00 PM",
    image: "img/7.jpg",
    lat: 21.1518,
    lng: -101.7125,
    address: "Universidad De La Salle Bajío, Entre Comunicación y Odontología",
    phone: "(477) 928-3746"
  },
  {
    id: 8,
    name: "Café Punta del Cielo",
    description: "El Gran Café de México, perfecto para mantenerte despierto durante las clases de idiomas.",
    priceRange: "$$$",
    distanceText: "4 min",
    category: "Café",
    schedule: "Lun-Vie: 7:00 AM - 9:00 PM",
    image: "img/8.jpg",
    lat: 21.1522,
    lng: -101.7110,
    address: "Universidad De La Salle Bajío, Facultad de Idiomas",
    phone: "(477) 102-9384"
  },
];
